### ISSUE TITLE
the ability to copy as well as directly translate any text (through another application)

### ISSUE THREAD

**Issue by Wjxfi** [toaq/toadua-android#8] opened 2023-07-23 21:09 UTC
the ability to copy as well as directly translate any text (through another application)

so that absolutely anyone can use your app. Through a translator. I use https://www.f-droid.org/packages/com.example.deeplviewer/, by the way :)

![c93b4582-9b59-470a-b4bb-01f1a616a39e.jpg](https://github.com/toaq/toadua-android/assets/113500363/5edc9c0e-e1f9-4b45-a958-36ccf1111dda)

This needs to be done for all locations in the app, please!

**Comment by robintown** [comment] 2023-07-31 18:32
Fixed in 07a6c8dea11609e46c0e03a220c17d0fab57ea2c

**Closed by robintown** 2023-07-31 18:32 UTC

**Comment by leafpool243** [comment] 2023-08-07 00:13
![Screenshot_20230806-170643](https://github.com/toaq/toadua-android/assets/63614345/3175a5fa-7d39-4d6c-b842-b1e1648d7a23)

@Wjxfi

It works for me. (I do not have DeepL translator installed so obviously there will not be the translate option there; only the copy option)

Have you installed the latest version? I used the version from Google Play store.

**Comment by robintown** [comment] 2023-08-07 02:20
@Wjxfi Thanks for noting, I was able to reproduce both issues and have opened #14 and #15 to track them. They appear to be upstream problems with the UI framework, so they're waiting for a fix from Google.
